c=g++ -std=c++11

main: main.cpp mtl_array.hpp mtl_iterator.hpp mtl_algorithm.hpp mtl_exception.hpp mtl_memory.hpp
	$c -o main main.cpp mtl_array.hpp mtl_iterator.hpp mtl_algorithm.hpp mtl_exception.hpp mtl_memory.hpp
