c=g++ -std=c++11

num_partition: number_of_partition.cpp
	$c -o num_partition number_of_partition.cpp

hanoi_tower: tower_of_hanoi.cpp
	$c -o hanoi_tower tower_of_hanoi.cpp

find_location: find_location.cpp
	$c -o find_location find_location.cpp

clean:
	rm -f a.out num_partition hanoi_tower find_location
